// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://diyickpovftuaplqaztu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeWlja3BvdmF0dWFwbHFhenR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MjAyMjksImV4cCI6MjA5MTM5NjIyOX0.kGF16fvsCkaOBYr9daK3qFJMg1tIEPdaaJmicIsoZ70";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);